name:        minq
version:     0.1.0.0
github:      "zdavep/minq"
author:      "David Pederson"
maintainer:  "dave.pederson@gmail.com"
copyright:   "Copyright the original author(s)"
description: Please see the README on GitHub at <https://github.com/zdavep/minq#readme>

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  minq-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - minq

tests:
  minq-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - minq
